---
version: "3.3"
services:
  deployer:
    image: deployer
    container_name: deployer
    build:
      context: .
    environment:
      - "ORG=${ORG}"
    volumes:
      - "${HOME}/.aws:/root/.aws"
      - "./docker:/app/docker"
      - "./jenkins:/app/jenkins"
      - "./terraform:/app/terraform"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
    stdin_open: true
    tty: true
