---
version: "3.3"
services:
  deployer:
    image: deployer
    container_name: deployer
    build:
      context: .
    environment:
      - "ORG=${ORG}"
      - "DOMAIN=${DOMAIN}"
      - "ENVIRONMENT=${ENVIRONMENT}"
      - "PROJECT=${PROJECT}"
      - "TOOLKIT_HOSTNAME=${TOOLKIT_HOSTNAME}"
      - "TOOLKIT_SKIP_PUSH=${TOOLKIT_SKIP_PUSH}"
      - "AWS_PROFILE=${AWS_PROFILE}"
      - "CERT_HOSTNAME_OVERRIDE=${CERT_HOSTNAME_OVERRIDE}"
    volumes:
      - "${HOME}/.aws:/root/.aws"
      - "./docker:/app/docker"
      - "./jenkins:/app/jenkins"
      - "./terraform:/app/terraform"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
    stdin_open: true
    tty: true
