---
version: "3.3"
services:
  toolkit:
    image: toolkit
    container_name: toolkit
    build:
      context: .
    volumes:
      - "./docker:/app/docker"
      - "./jenkins:/app/jenkins"
      - "./terraform:/app/terraform"
    stdin_open: true
    tty: true
