version: "3.3"
services:
  toolkit:
    container_name: "toolkit"
    build:
      context: .
    image: "toolkit"
    ports:
      - 8080:8080
      - 127.0.0.1:50000:50000
    volumes:
      - "./jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
volumes:
  jenkins_home:
